---
# tasks file for ansible-role-sshd-host-keys-client

- name: Generate the ssh host certificate
  command: "/usr/bin/curl -o /etc/ssh/{{ ssh_host_key_cert }} -F file=@/etc/ssh/{{ ssh_host_key_pub }} {{ ssh_hostca_url }}" 
  args:
    creates: "/etc/ssh/{{ ssh_host_key_cert }}"
  notify: restart sshd

- name: Add HostCertificate line to sshd_config
  lineinfile: dest=/etc/ssh/sshd_config regexp="^HostCertificate" line="HostCertificate /etc/ssh/{{ ssh_host_key_cert }}"
  notify: restart sshd

- name: Get the ssh known_hosts with the host CA
  uri: 
    url="{{ ssh_hostca_url}}"
    return_content=yes
  register: known_hosts

- name: Add the known_hosts entry with the host CA to known_hosts
  lineinfile: dest=/etc/ssh/ssh_known_hosts regexp="^@cert-authority" line="{{ known_hosts.content }}"

- name: Add Canonicalize options to ssh_config
  blockinfile:
    dest: /etc/ssh/ssh_config
    block: |
      CanonicalizeHostname yes
      CanonicalizeFallbackLocal yes
      CanonicalDomains "{{ ssh_canonicaldomains }}"
